apiVersion: apps/v1
kind: Deployment
metadata:
  name: obesity-deployment
  labels:
    app: obesity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obesity-api
  template:
    metadata:
      labels:
        app: obesity-api
    spec:
      containers:
      - name: obesity-container
        image: ashxivy/applied_statistics:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "models/best_model.joblib"
        - name: MODEL_S3_URL
          value: "s3://edq/models/best_model.joblib"
        - name: AWS_S3_ENDPOINT_URL
          value: "https://minio.lab.sspcloud.fr"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access_key
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret_key
              optional: true
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: session_token
              optional: true
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"